name       : four-in-a-row
version    : 3.22.2
release    : 2
source     :
    - https://download.gnome.org/sources/four-in-a-row/3.22/four-in-a-row-3.22.2.tar.xz : bc4194e8ab6d1d2a6a63a2e91945cd5465f49ebf0dae2eecacc66e69db56a420
license    :
    - GPL-2.0
    - GPL-3.0
component  : games.strategy
summary    : Build a line of four of your marbles while trying to stop your opponent building a line of his or her own.
description: |
    The objective of Four-in-a-row is to build a line of four of your marbles while trying to stop your opponent (human or computer) building a line of his or her own. A line can be horizontal, vertical or diagonal.
builddeps  :
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libcanberra)
    - pkgconfig(librsvg-2.0)
    - itstool
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
