name       : four-in-a-row
version    : 3.32.0
release    : 4
source     :
    - https://download.gnome.org/sources/four-in-a-row/3.32/four-in-a-row-3.32.0.tar.xz : f4a74ee13b1fc846f5045817477c3416551386a2bbf6a5d37da39fdbe6aa9c40
license    :
    - GPL-2.0
    - GPL-3.0
component  : games.strategy
summary    : Build a line of four of your marbles while trying to stop your opponent building a line of his or her own.
description: |
    The objective of Four-in-a-row is to build a line of four of your marbles while trying to stop your opponent (human or computer) building a line of his or her own. A line can be horizontal, vertical or diagonal.
builddeps  :
    - pkgconfig(appstream-glib)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libcanberra)
    - pkgconfig(librsvg-2.0)
    - pkgconfig(yelp-xsl)
    - itstool
    - vala
    - yelp-tools
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
