name       : four-in-a-row
version    : 3.22.1
release    : 1
source     :
    - https://download.gnome.org/sources/four-in-a-row/3.22/four-in-a-row-3.22.1.tar.xz : 3ccf65a9da08d8e888fa90a7bf55192bc344981cec3b1f56fa0da70f423137d4
license    :
    - GPL-2.0
    - GPL-3.0
component  : games.strategy
summary    : Build a line of four of your marbles while trying to stop your opponent building a line of his or her own.
description: |
    The objective of Four-in-a-row is to build a line of four of your marbles while trying to stop your opponent (human or computer) building a line of his or her own. A line can be horizontal, vertical or diagonal.
builddeps  :
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libcanberra)
    - pkgconfig(librsvg-2.0)
    - itstool
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
